enum ValidationEnum { validated, unValidated }
enum ValidationTagEnum { NOT_EMPTY,EMPTY, NOT_EQUAL,EQUAL,EMAIL_ADDRESS,SHOULD_BE_NUMBER,BETWEEN ,MATCHES,MUST}
enum DateValidationType {
  IS_DATE_EQUAL,
  IS_FIRST_DATE_GRATER,
  IS_FIRST_DATE_SMALLER,
  IS_FIRST_DATE_GRATER_OR_EQUAL,
  IS_FIRST_DATE_SMALLER_OR_EQUAL,
}

